[phases.setup]
cmds = ["corepack enable"]

[phases.build]
cmds = [
  "pnpm install --frozen-lockfile",
  "pnpm build",
  "cp -r apps/web/public apps/web/.next/standalone/apps/web/public",
  "cp -r apps/web/.next/static apps/web/.next/standalone/apps/web/.next/static",
]
